-- ReflowTask initial schema.
--
-- Timestamps are wall-clock (TIMESTAMP WITHOUT TIME ZONE / LocalDateTime) on purpose:
-- this is a single-user personal scheduler in one timezone, where "9:00 means 9:00"
-- is the correct semantic. An instant-based column would make DST shift the user's
-- working hours.
--
-- Syntax is kept to what both H2 2.x and PostgreSQL 10+ accept, so dev and prod run
-- the exact same migrations.

CREATE TABLE task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(200)  NOT NULL,
    description       VARCHAR(2000),
    estimated_minutes INTEGER       NOT NULL,
    -- NULL means no deadline. A date-only deadline is stored as 23:59 of that day,
    -- with deadline_has_time = FALSE so the UI can render "Fri" instead of "Fri 23:59".
    deadline          TIMESTAMP,
    deadline_has_time BOOLEAN       NOT NULL DEFAULT FALSE,
    priority          VARCHAR(10)   NOT NULL,
    status            VARCHAR(20)   NOT NULL,
    created_at        TIMESTAMP     NOT NULL,
    CONSTRAINT task_estimated_minutes_positive CHECK (estimated_minutes > 0)
);

CREATE INDEX idx_task_status ON task (status);

-- A task has 0..N blocks: the scheduler splits work that does not fit one free slot.
CREATE TABLE time_block (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id  BIGINT    NOT NULL REFERENCES task (id) ON DELETE CASCADE,
    start_at TIMESTAMP NOT NULL,
    end_at   TIMESTAMP NOT NULL,
    -- Pinned blocks are immovable: replanning treats them as obstacles and never
    -- recreates them. This is what lets a fixed appointment survive a reflow.
    pinned   BOOLEAN   NOT NULL DEFAULT FALSE,
    CONSTRAINT time_block_ends_after_start CHECK (end_at > start_at)
);

CREATE INDEX idx_time_block_start_at ON time_block (start_at);
CREATE INDEX idx_time_block_task_id ON time_block (task_id);

-- Every replan is recorded. PRODUCT.md forbids silent schedule mutation, so this
-- table is the user-visible evidence that something moved and why.
CREATE TABLE reschedule_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at  TIMESTAMP   NOT NULL,
    -- "trigger" is reserved in PostgreSQL.
    trigger_type VARCHAR(20) NOT NULL,
    summary      VARCHAR(500)
);

CREATE INDEX idx_reschedule_event_occurred_at ON reschedule_event (occurred_at DESC);

CREATE TABLE reschedule_event_item (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          BIGINT      NOT NULL REFERENCES reschedule_event (id) ON DELETE CASCADE,
    -- Nulled rather than cascaded when a task is deleted: history that disappears
    -- with its task is not history. task_title keeps the entry readable.
    task_id           BIGINT      REFERENCES task (id) ON DELETE SET NULL,
    task_title        VARCHAR(200) NOT NULL,
    kind              VARCHAR(20) NOT NULL,
    previous_start_at TIMESTAMP,
    new_start_at      TIMESTAMP
);

CREATE INDEX idx_reschedule_event_item_event_id ON reschedule_event_item (event_id);

-- One row per weekday the user works. A weekday with no row is not a working day,
-- which makes "I don't work Fridays" a deletion rather than a special case.
CREATE TABLE working_hours (
    day_of_week SMALLINT PRIMARY KEY,
    start_time  TIME NOT NULL,
    end_time    TIME NOT NULL,
    CONSTRAINT working_hours_day_of_week_iso CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT working_hours_ends_after_start CHECK (end_time > start_time)
);

-- Recurring unavailable time inside working hours, e.g. a lunch break.
CREATE TABLE blocked_period (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week SMALLINT NOT NULL,
    start_time  TIME     NOT NULL,
    end_time    TIME     NOT NULL,
    label       VARCHAR(100),
    CONSTRAINT blocked_period_day_of_week_iso CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT blocked_period_ends_after_start CHECK (end_time > start_time)
);

CREATE INDEX idx_blocked_period_day_of_week ON blocked_period (day_of_week);

-- Single-row settings table; the CHECK is what keeps it single-row.
CREATE TABLE scheduling_settings (
    id                SMALLINT PRIMARY KEY,
    horizon_days      INTEGER NOT NULL,
    min_chunk_minutes INTEGER NOT NULL,
    CONSTRAINT scheduling_settings_single_row CHECK (id = 1),
    CONSTRAINT scheduling_settings_horizon_positive CHECK (horizon_days > 0),
    CONSTRAINT scheduling_settings_min_chunk_positive CHECK (min_chunk_minutes > 0)
);
