-- Household login: each person gets their own username and password, with one admin who
-- can see and manage every account. Reachable only over the existing LAN/Tailscale boundary,
-- so this is deliberately not a full account system - no email, no password reset, no roles
-- beyond ADMIN/MEMBER.

CREATE TABLE app_user (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              VARCHAR(50)  NOT NULL,
    password_hash         VARCHAR(100) NOT NULL,
    role                  VARCHAR(10)  NOT NULL,
    must_change_password  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMP    NOT NULL,
    CONSTRAINT app_user_username_unique UNIQUE (username),
    CONSTRAINT app_user_role_valid CHECK (role IN ('ADMIN', 'MEMBER'))
);

-- Opaque random token as its own primary key, so the session cookie's value is itself the
-- lookup key and nothing else needs to be derived from it.
CREATE TABLE user_session (
    id         VARCHAR(64) PRIMARY KEY,
    user_id    BIGINT    NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_user_session_user_id ON user_session (user_id);

-- Bootstrap admin, password 'changeme' (bcrypt hash below), forced to change it before doing
-- anything else. The operator already has SSH/physical control of the box; the actual exposure
-- window is closed by changing this password immediately after deploying this migration, not
-- by generating a random one here.
INSERT INTO app_user (id, username, password_hash, role, must_change_password, created_at) VALUES
    (1, 'admin', '$2b$10$t2YUtyzUEzW1Zjqo7I5qK.dZtl9WPry/gkE76dT93W8d1njJ.ovIi', 'ADMIN', TRUE, CURRENT_TIMESTAMP);

-- The identity generator's counter is untouched by an INSERT that supplies its own id, so the
-- very next generated id would otherwise also be 1 and collide with the seeded admin.
ALTER TABLE app_user ALTER COLUMN id RESTART WITH 2;
