-- scheduling_settings was a hardcoded singleton (id fixed at 1, enforced by a CHECK). One row
-- per user replaces one row globally, so the singleton id becomes a normal generated identity
-- and a unique user_id takes over the "at most one row" job the CHECK used to do. The table is
-- recreated rather than altered in place because changing an existing column to a generated
-- identity is not portable between H2 and PostgreSQL.
-- Constraint names are suffixed _v2 because H2, unlike PostgreSQL, scopes named constraints to
-- the whole schema rather than per-table, and the original table still exists side by side with
-- this one until the DROP TABLE below.
CREATE TABLE scheduling_settings_v2 (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT  NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    horizon_days      INTEGER NOT NULL,
    min_chunk_minutes INTEGER NOT NULL,
    buffer_minutes    INTEGER NOT NULL DEFAULT 0,
    onboarded         BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT scheduling_settings_user_unique_v2 UNIQUE (user_id),
    CONSTRAINT scheduling_settings_horizon_positive_v2 CHECK (horizon_days > 0),
    CONSTRAINT scheduling_settings_min_chunk_positive_v2 CHECK (min_chunk_minutes > 0),
    CONSTRAINT scheduling_settings_buffer_not_negative_v2 CHECK (buffer_minutes >= 0)
);
INSERT INTO scheduling_settings_v2 (user_id, horizon_days, min_chunk_minutes, buffer_minutes, onboarded)
    SELECT 1, horizon_days, min_chunk_minutes, buffer_minutes, onboarded FROM scheduling_settings;
DROP TABLE scheduling_settings;
ALTER TABLE scheduling_settings_v2 RENAME TO scheduling_settings;
