-- Calendar sync, both ways.
--
-- Out: each person may turn on a secret subscription link (calendar_token) that calendar apps
-- poll for their planned blocks. The token is the whole credential, so it is long, random,
-- unique, and can be replaced or cleared at any time.
ALTER TABLE app_user ADD COLUMN calendar_token VARCHAR(64);
ALTER TABLE app_user ADD CONSTRAINT app_user_calendar_token_unique UNIQUE (calendar_token);

-- In: other calendars (a Nextcloud share link, any .ics URL) whose events count as busy time.
CREATE TABLE calendar_source (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name            VARCHAR(100) NOT NULL,
    url             VARCHAR(2000) NOT NULL,
    last_fetched_at TIMESTAMP,
    -- Why the last refresh failed, shown to the person; null when it worked.
    last_error      VARCHAR(500)
);

CREATE INDEX idx_calendar_source_user_id ON calendar_source (user_id);

-- The busy intervals read from a source at its last refresh, replaced wholesale on each one.
-- A cache of someone else's calendar, not history: removing the source removes them.
CREATE TABLE external_busy (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT       NOT NULL REFERENCES calendar_source (id) ON DELETE CASCADE,
    user_id   BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    start_at  TIMESTAMP    NOT NULL,
    end_at    TIMESTAMP    NOT NULL,
    title     VARCHAR(200),
    CONSTRAINT external_busy_ends_after_start CHECK (end_at > start_at)
);

CREATE INDEX idx_external_busy_user_start ON external_busy (user_id, start_at);
